[package]
name = "sudoku_solving"
version = "0.1.0"
authors = ["Markus Mayer"]
edition = "2021"

[dependencies]
sudoku = { path = "../../lib/sudoku" }
visitor = { path = "../../lib/visitor" }
log = "0.4.17"
env_logger = "0.9.3"
clap = "4.0.26"
